Imports System.Data.SqlClient
Imports System.Drawing.Printing
Imports System.Text


Public Class MonthlyUserLoginReport

    Private strManager As String = UserLogin.strCurrentLoginStaffName
    Private userLoginList As New List(Of String)

    Private Sub MonthlyUserLoginReport_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        cboYear.SelectedIndex = 0
        cboMonth.SelectedIndex = 0
    End Sub

    Private Sub btnGenerate_Click(sender As Object, e As EventArgs) Handles btnGenerate.Click
        With userLoginReportPreview
            .Document = printUserLoginReport
            .ShowDialog(Me)
        End With
    End Sub


    Private Sub printUserLoginReport_PrintPage(sender As Object, e As PrintPageEventArgs) Handles printUserLoginReport.PrintPage
        userLoginList.Clear()

        Dim sdr As SqlDataReader
        Dim sql As String

        Dim staffRecord As New StringBuilder()
        Dim recordItems() As String

        Dim intCount As Integer = 0
        Static intPage As Integer = 1
        Dim intCountRecords As Integer = 0

        Dim strMonth As String = cboMonth.SelectedIndex + 1
        Dim strMonthDisplay As String = cboMonth.SelectedItem.ToString
        Dim strYear As String = cboYear.SelectedItem.ToString
        Dim strYearDisplay As String = cboYear.SelectedItem.ToString

        Dim fntHeaderInventoryStock As New Font("Century Gothic", 28)
        Dim fntHeaderAddressInfo As New Font("Century Gothic", 12)
        Dim formatHeaderAddressInfo As StringFormat = New StringFormat()
        formatHeaderAddressInfo.Alignment = StringAlignment.Center
        formatHeaderAddressInfo.LineAlignment = StringAlignment.Center
        Dim fntSubHeader As New Font("Century Gothic", 12.5)
        Dim fntContent As New Font("Century Gothic", 14)
        Dim fntFooter As New Font("Century Gothic", 13)
        Dim fntMonthYear As New Font("Century Gothic", 26)

        Dim strHeader As String = "Monthly Staff Joined Report"
        Dim strAddress As String = "BOOK MASTER" & vbNewLine & "Ground Floor, Tan Sri Khaw Kai Boh Building, Kampus Utama, Jalan Genting Kelang," & vbNewLine & "53300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur" & vbNewLine & "Tel: +(603)-4145 0123"
        Dim strSubHeader As String = String.Format(vbNewLine & " Printed on {0:dd-MMMM-yyyy hh:mm:ss tt}" & vbNewLine &
        " Generated by " + strManager, DateTime.Now)
        Dim strMonthYear As String = "Month : " & strMonthDisplay & " Year : " & strYear

        If OpenConnection() = True Then

            Try
                sql = "Select logID, loginTime, logoutTime, staffID from UserLogTime Where Month(loginTime) = @strMonth And Year(loginTime) = @strYear"
                Dim cmd As SqlCommand = New SqlCommand(sql, conn)
                cmd.Parameters.AddWithValue("@strMonth", strMonth)
                cmd.Parameters.AddWithValue("@strYear", strYear)

                sdr = cmd.ExecuteReader()
                If sdr.HasRows Then
                    While sdr.Read
                        userLoginList.Add(sdr.GetValue(0).ToString() & vbTab & sdr.GetValue(1).ToString() & vbTab & sdr.GetValue(2).ToString() & vbTab & sdr.GetValue(3).ToString())
                        intCount += 1
                    End While
                End If

                staffRecord.AppendLine("                                                                      ")
                staffRecord.AppendLine("No   Login ID                 Login Time                 LogoutTime                 Staff ID")
                staffRecord.AppendLine("==   =============   ================   ================   ======= ")
                For Each item In userLoginList
                    recordItems = CStr(item).Split(CChar(vbTab))
                    intCountRecords += 1
                    staffRecord.AppendFormat(" {0,2}  {1,15}    {2,-6}   {3,-20}     {4,-20}       " & vbNewLine, intCountRecords, recordItems(0), recordItems(1), recordItems(2), recordItems(3))
                Next
                staffRecord.AppendLine()
                staffRecord.AppendLine("_______________________________________________________________________________")
                staffRecord.AppendLine()
                staffRecord.AppendFormat("{0, 2} record(s) found.", intCount)

                With e.Graphics
                    .DrawImage(My.Resources.BookMasterLogo, 200, 20, 450, 80)
                    .DrawString(strHeader, fntHeaderInventoryStock, Brushes.Black, 170, 110)
                    .DrawString(strAddress, fntHeaderAddressInfo, Brushes.Black, 430, 200, formatHeaderAddressInfo)
                    .DrawString(strSubHeader, fntSubHeader, Brushes.Black, 30, 250)
                    .DrawString(strMonthYear, fntMonthYear, Brushes.Black, 290, 320)
                    .DrawString(staffRecord.ToString(), fntContent, Brushes.Black, 30, 350)
                    .DrawString("Page(s) " & intPage & " of " & intPage, fntFooter, Brushes.Black, 30, e.MarginBounds.Bottom)
                End With


            Catch ex As Exception
                MessageBox.Show(ex.ToString, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
                Me.Close()
            End Try

            CloseConnection()

        End If


    End Sub
End Class