Imports System.Data.SqlClient
Imports System.Drawing.Printing
Imports System.Text

Public Class MonthlyStaffJoinedReport

    Private strManager As String = UserLogin.strCurrentLoginStaffName
    Private staffRecordList As New List(Of String)

    Private Sub btnGenerate_Click_(sender As Object, e As EventArgs) Handles btnGenerate.Click

        With staffReportPreview
            .Document = printStaffReport
            .ShowDialog(Me)
        End With

    End Sub

    Private Sub printStaffReport_PrintPage(sender As Object, e As PrintPageEventArgs) Handles printStaffReport.PrintPage
        staffRecordList.Clear()

        Dim sdr As SqlDataReader
        Dim sql As String

        Dim staffRecord As New StringBuilder()
        Dim recordItems() As String

        Dim bodyForCount As New StringBuilder()
        Dim bodyForStaffID As New StringBuilder()
        Dim bodyForStaffName As New StringBuilder()
        Dim bodyForStaffRole As New StringBuilder()
        Dim bodyForStaffType As New StringBuilder()
        Dim bodyForJoinedDate As New StringBuilder()
        Dim bodyForCountResult As New StringBuilder()

        Dim intCount As Integer = 0
        Static intPage As Integer = 1
        Dim intCountRecords As Integer = 0

        Dim strMonth As String = cboMonth.SelectedIndex + 1
        Dim strMonthDisplay As String = cboMonth.SelectedItem.ToString
        Dim strYear As String = cboYear.SelectedItem.ToString
        Dim strYearDisplay As String = cboYear.SelectedItem.ToString

        Dim fntHeaderInventoryStock As New Font("Century Gothic", 28)
        Dim fntHeaderAddressInfo As New Font("Century Gothic", 12)
        Dim formatHeaderAddressInfo As StringFormat = New StringFormat()
        formatHeaderAddressInfo.Alignment = StringAlignment.Center
        formatHeaderAddressInfo.LineAlignment = StringAlignment.Center
        Dim fntSubHeader As New Font("Century Gothic", 12.5)
        Dim fntContent As New Font("Century Gothic", 14)
        Dim fntFooter As New Font("Century Gothic", 13)
        Dim fntMonthYear As New Font("Century Gothic", 26)

        Dim strHeader As String = "Monthly Staff Joined Report"
        Dim strAddress As String = "BOOK MASTER" & vbNewLine & "Ground Floor, Tan Sri Khaw Kai Boh Building, Kampus Utama, Jalan Genting Kelang," & vbNewLine & "53300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur" & vbNewLine & "Tel: +(603)-4145 0123"
        Dim strSubHeader As String = String.Format(vbNewLine & " Printed on {0:dd-MMMM-yyyy hh:mm:ss tt}" & vbNewLine &
        " Generated by " + strManager, DateTime.Now)
        Dim strMonthYear As String = "Month : " & strMonthDisplay & " Year : " & strYear

        If OpenConnection() = True Then

            Try
                sql = "Select staffID,  staffName, staffRole,staffType,joinedDate from Staff Where Month(joinedDate) = @strMonth And Year(joinedDate) = @strYear"
                Dim cmd As SqlCommand = New SqlCommand(sql, conn)
                cmd.Parameters.AddWithValue("@strMonth", strMonth)
                cmd.Parameters.AddWithValue("@strYear", strYear)

                sdr = cmd.ExecuteReader()
                If sdr.HasRows Then
                    While sdr.Read
                        Dim strJoinedDate As String = String.Format("{0:dd/MM/yyyy }", sdr.GetValue(4))
                        staffRecordList.Add(sdr.GetValue(0).ToString() & vbTab & sdr.GetValue(1).ToString() & vbTab & sdr.GetValue(2).ToString() & vbTab & sdr.GetValue(3).ToString() & vbTab & strJoinedDate)
                        intCount += 1
                    End While
                End If

                staffRecord.AppendLine("                                                                      ")
                staffRecord.AppendLine("No  Staff ID    Staff Name                 Joined Date      Staff Role       Staff Type ")
                staffRecord.AppendLine("==  =======  ==========                ==========      =========    ==========")
                For Each item In staffRecordList
                    recordItems = CStr(item).Split(CChar(vbTab))
                    intCountRecords += 1

                    bodyForCount.AppendFormat("{0,7} {1}" & vbNewLine, " ", intCountRecords)
                    bodyForStaffID.AppendFormat("{0,13} {1}" & vbNewLine, " ", recordItems(0))
                    bodyForStaffName.AppendFormat("{0,30} {1}" & vbNewLine, " ", recordItems(1))
                    bodyForStaffRole.AppendFormat("{0,97} {1}" & vbNewLine, " ", recordItems(2))
                    bodyForStaffType.AppendFormat("{0,120} {1}" & vbNewLine, " ", recordItems(3))
                    bodyForJoinedDate.AppendFormat("{0,70} {1}" & vbNewLine, " ", recordItems(4))

                    'staffRecord.AppendFormat(" {0,2} {1,6}  {2, -15} {3,10} {4,9} {5,7} " & vbNewLine, intCountRecords, recordItems(0), recordItems(1), recordItems(4), recordItems(3), recordItems(2))
                Next
                bodyForCountResult.AppendLine()
                bodyForCountResult.AppendLine("_______________________________________________________________________________")
                bodyForCountResult.AppendLine()
                bodyForCountResult.AppendFormat("{0} record(s) found.", intCount)

                With e.Graphics
                    .DrawImage(My.Resources.BookMasterLogo, 200, 20, 450, 80)
                    .DrawString(strHeader, fntHeaderInventoryStock, Brushes.Black, 170, 110)
                    .DrawString(strAddress, fntHeaderAddressInfo, Brushes.Black, 430, 200, formatHeaderAddressInfo)
                    .DrawString(strSubHeader, fntSubHeader, Brushes.Black, 30, 250)
                    .DrawString(strMonthYear, fntMonthYear, Brushes.Black, 280, 310)
                    .DrawString(staffRecord.ToString(), fntContent, Brushes.Black, 40, 350)
                    .DrawString(bodyForCount.ToString(), fntContent, Brushes.Black, 0, 420)
                    .DrawString(bodyForStaffID.ToString(), fntContent, Brushes.Black, 0, 420)
                    .DrawString(bodyForStaffName.ToString(), fntContent, Brushes.Black, 0, 420)
                    .DrawString(bodyForStaffRole.ToString(), fntContent, Brushes.Black, 0, 420)
                    .DrawString(bodyForStaffType.ToString(), fntContent, Brushes.Black, 0, 420)
                    .DrawString(bodyForJoinedDate.ToString(), fntContent, Brushes.Black, 0, 420)
                    .DrawString(bodyForCountResult.ToString(), fntContent, Brushes.Black, 0, 850)
                    .DrawString("Page(s) " & intPage & " of " & intPage, fntFooter, Brushes.Black, 30, e.MarginBounds.Bottom)
                End With


            Catch ex As Exception
                MessageBox.Show(ex.ToString, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
                Me.Close()
            End Try

            CloseConnection()

        End If

    End Sub

    Private Sub NewStaffJoinedReport_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        cboYear.SelectedIndex = 0
        cboMonth.SelectedIndex = 0
    End Sub
End Class